# MySQL.  Versions 4.1 and 5.0 are recommended.
#
#
# Be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
      host: localhost
      adapter: jdbcmysql
      database: design_connect_production
      port: 3306
      username: root
      password:

production:
      host: localhost
      adapter: mysql
      database: design_connect_production
      port: 3306
      username: root
      password:

